# Generated by Django 3.1.4 on 2021-04-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='adress',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
